#!/usr/bin/env bash

set -eux

# get rust
curl https://sh.rustup.rs -sSf | sh -s -- -y

echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.bashrc

source ~/.bashrc

# install prolog package
cat << EOF > install.pl
:- initialization main.

install:-
        pack_install(terminus_store_prolog).

main:-
        catch(install, E, (print_message(error, E), fail)),
        halt.
main:-
        halt(1).
EOF

swipl install.pl

# get server source
git clone https://github.com/terminusdb/terminusdb-server


# make launcher script
cat << EOF > start_terminusdb.sh
cd ${HOME}/terminusdb-server
./utils/db_init -k "${NB_USER}" -s "${NB_USER}" -p "${PORT}"
./start.pl
EOF

# configure proxy
cat << EOF > $HOME/.jupyter/jupyter_notebook_config.d/terminusdb-server-proxy.json
{
    "ServerProxy": {
        "servers": {
            "terminusdb": {
                "command": ["./start_terminusdb.sh"],
                "environment": {
                    "PORT": "{port}"
                },
                "timeout": 1000
            }
        }
    }
}
EOF

# install labextensions
jupyter labextension install --no-build --debug \
    @jupyter-widgets/jupyterlab-manager \
    jupyter-cytoscape \
    bqplot

# build lab
jupyter lab build --debug --minimize=False
